### ISSUE TITLE
Feature: Studio Lists

### ISSUE THREAD

**Issue by Mikeput** [RiffSphere/Collectarr#3]
Possible to get films made by studios in the library, similar to actors but studios?

**Comment by RiffSphere** [comment]
Studios are not supported by Radarr, and would need semi-constant monitoring for new movies.
This tool is made primarily to check if movies in Radarr belong to a collection, and enable collection monitoring in Radarr.
It also allows to make a watchlist for actors, but this is also done by analyzing current movies and provide a list to Radarr.
For studios, other tools are available that will build and update lists, that can then be provided to Radarr.

Request is out of scope for this tool.
